apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx
    command: [ "/bin/sh" ]
    args: ["-c","ls -ltr /tmp"]
    volumeMounts:
     - name: workdir
       mountPath: /tmp
  initContainers:
  - name: init-myfile
    image: nginx
    command: [ "/bin/sh" ]
    args: ["-c","mkdir -p /work-dir/myfile"]
    volumeMounts:
     - name: workdir
       mountPath: "/work-dir"
  volumes:
   - name: workdir
     emptyDir: {} 
