kind: DeploymentConfig
apiVersion: v1
metadata:
  name: env-pod
spec:
  template:
    metadata:
      labels:
        name: env-pod
    spec:
      containers:
        - name: nginx
          image: nginx
          command: [ "/bin/sh" ]
          args: ["-c","while true; do echo ${ENV_USERNAME}; sleep 10; done"]
          env:
          - name: ENV_USERNAME
            value: ${ENV_USERNAME}
          - name: ENV_PASSWORD
            value: ${ENV_PASSWORD}
  replicas: 1
  selector:
    name: env-pod
