apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeapp
  name: nodeapp-1
spec:
  ports:
    - port: 8080
      nodePort: 30036
      name: http
  selector:
    app: nodeapp
    deploymentconfig: nodeapp
  sessionAffinity: None
  type: NodePort


