apiVersion: v1
kind: Service
metadata:
  labels:
    app: dapi-test-pod
  name: dapi-test-pod
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dapi-test-pod
    deploymentconfig: dapi-test-pod
  type: ClusterIP

